import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

export const getStaticProps = async () => {
  return {
    props: {}
  }
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Welcome to my portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
      </main>

      <footer>
       
      </footer>
    </div>
  )
}

export default Home
